stages:
  - testing
  - deploy

variables:
  REGISTRY: "registry.gitlab.com/erzh/laravel_cicd"

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

dev_start:
  stage: testing
  tags:
    - test
  only:
    - master
  script:
    - docker build --build-arg NODE_ENV="dev" -t "$REGISTRY/dev/app:$CI_COMMIT_SHA" -f ./Dockerfile .
    - docker push "$REGISTRY/dev/app:$CI_COMMIT_SHA"


dev_deploy:
  stage: deploy
  tags:
    - prod
  only:
    - tags
  when: manual
  script:
    - export CONTAINER_PREFIX=laravel-roadrunner-in-docker
    - docker stop $(docker ps -a | grep ${CONTAINER_PREFIX}_ | awk '{print $1}')_1 || true
    - docker rm $(docker ps -a | grep ${CONTAINER_PREFIX}_ | awk '{print $1}')_1 || true
    - docker volume rm $(docker volume ls | grep ${CONTAINER_PREFIX}_ | awk '{print $2}')_1 || true
    - docker-compose -p $CONTAINER_PREFIX -f docker-compose.yml up -d
    - docker exec ${CONTAINER_PREFIX}_web_1 composer update
    - docker exec ${CONTAINER_PREFIX}_web_1 composer install
    - docker exec ${CONTAINER_PREFIX}_web_1 php artisan migrate
    - docker exec ${CONTAINER_PREFIX}_web_1 php artisan cache:clear
    - docker exec ${CONTAINER_PREFIX}_web_1 php artisan config:cache
